version: "3.8"
services:
  backend-go:
    environment:
      FRONTEND_URL: "http://localhost:3000"
      BACKEND_URL: "http://localhost:8080"
      PORT: 8080
    build: 
      context: ./backend-go
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend-go:/backend-go
    command: air

  frontend-react-js:
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:8080"
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js:/frontend-react-js
      - /frontend-react-js/node_modules

networks:
  internal-network:
    driver: bridge
    name: buzzer